In [1]:
import torch

In [2]:
#  pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu118

# Tensors

In [8]:
#Number
t1 = torch.tensor(4.)
t1

tensor(4.)

In [9]:
t1.dtype

torch.float32

In [10]:
#vector
t2 = torch.tensor([1., 2, 3, 4])
t2

tensor([1., 2., 3., 4.])

In [6]:
t2.dtype

torch.float32

In [13]:

#Matrix
#2-dimensional
t3 = torch.tensor([[5., 6],
                  [7, 8],
                  [9, 10]])
t3




tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [14]:
#3D tensors
t4 = torch.tensor([
    [[11, 12, 13],
     [13, 14, 15]],
    [[15, 16, 17],
     [17, 18, 19.]]])
t4


tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

In [15]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [16]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [17]:
print(t3)
t3.shape

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


torch.Size([3, 2])

In [18]:
print(t4)
t4.shape

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])


torch.Size([2, 2, 3])

# Tensor Operations and gradients